# Crosswalk with FAIR4RS Principles

This document summarizes how sPARcRNA_Viz aligns with the FAIR4RS Principles. We provide a brief explanation of compliance for each principle to help users understand how the software meets these standards. Compliance is scored on a scale of 0 to 2:

- 0: No compliance
- 1: Partial compliance
- 2: Full compliance
- N/A: Not applicable to the software

Our assessment is based on information from the software repository and the Zenodo record.

| FAIR4RS Principle                                                                                      | Score | Explanation                                                                                                                                                                                                                                                                             |
| ------------------------------------------------------------------------------------------------------ | ----- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| F1. Software is assigned a globally unique and persistent identifier.                                  | 2     | Our software has been assigned a Digital Object Identifier (DOI) through Zenodo, ensuring a unique and persistent identifier. Additionally, our software is archived in Software Heritage, providing another layer of identification and preservation.                                  |
| F1.1. Components of the software representing levels of granularity are assigned distinct identifiers. | 2     | Software components are assigned distinct identifiers using SoftWare Heritage persistent IDentifier (SWHID). This system provides unique identifiers for various elements such as source code, releases, files, commits, and even code fragments, ensuring fine-grained identification. |
| F1.2. Different versions of the software are assigned distinct identifiers.                            | 2     | We use Semantic Versioning (SemVer) for version control. Each software version receives a unique identifier through the Zenodo release process. Software Heritage also preserves each version of our software, assigning distinct SWHIDs to different releases and commits.             |
| F2. Software is described with rich metadata.                                                          | 2     | Comprehensive metadata is provided in the Zenodo record, including title, authors, description, keywords, license, and funding information. We've also included codemeta.json and CITATION.cff files in the repository.                                                                 |
| F3. Metadata clearly and explicitly include the identifier of the software they describe.              | 2     | The software's DOI is clearly included in the metadata. The SWHID is also available through Software Heritage.                                                                                                                                                                          |
| F4. Metadata are FAIR, searchable and indexable.                                                       | 2     | Metadata is provided in machine-readable JSON format and is indexed by Zenodo, ensuring it is FAIR, searchable, and indexable. Software Heritage also indexes our software and its metadata, enhancing discoverability.                                                                 |
| A1. Software is retrievable by its identifier using a standardised communications protocol.            | 2     | The software can be retrieved via HTTP protocol using its identifier. Zenodo provides a standardized method for accessing the software.                                                                                                                                                 |
| A1.1. The protocol is open, free, and universally implementable.                                       | 2     | Zenodo is an open-access repository, ensuring the protocol is open, free, and universally implementable. Software Heritage also provides open access to archived software.                                                                                                              |
| A1.2. The protocol allows for an authentication and authorization procedure, where necessary.          | N/A   | Our application is publicly available and does not require authentication or authorization.                                                                                                                                                                                             |
| A2. Metadata are accessible, even when the software is no longer available.                            | 2     | Metadata is stored in Zenodo and remains accessible via DOI even if the software becomes unavailable.                                                                                                                                                                                   |
| I1. Software reads, writes and exchanges data in a way that meets domain-relevant community standards. | 2     | We use JSON and CSV file formats, which are widely accepted in the bioinformatics community.                                                                                                                                                                                            |
| I2. Software includes qualified references to other objects.                                           | 0     | Currently, the software does not include qualified references to other objects.                                                                                                                                                                                                         |
| R1. Software is described with a plurality of accurate and relevant attributes.                        | 2     | The metadata provides comprehensive information about the software, including title, authors, description, keywords, license, and funding details.                                                                                                                                      |
| R1.1. Software is given a clear and accessible license.                                                | 2     | The software is licensed under the MIT License, a permissive open-source license. This license information is preserved in both Zenodo and Software Heritage.                                                                                                                           |
| R1.2. Software is associated with detailed provenance.                                                 | 2     | Detailed provenance information, including authors, contributors, and funding, is provided in the metadata and README file. Software Heritage preserves the entire development history, enhancing provenance tracking.                                                                  |
| R2. Software includes qualified references to other software.                                          | 0     | At present, the software does not include qualified references to other software.                                                                                                                                                                                                       |
| R3. Software meets domain-relevant community standards.                                                | 0     | The software does not currently meet all domain-relevant community standards.                                                                                                                                                                                                           |

This assessment highlights areas where sPARcRNA_Viz excels in FAIR principles and identifies opportunities for improvement. We welcome feedback and suggestions for enhancing our alignment with these principles.
